image: node:14

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

before_script:
  # Install dependencies for client and server
  - cd client && npm install && cd ..
  - cd Server && npm install && cd ..

install:
  stage: install
  script:
    - echo "Dependencies installed during before_script"

build:
  stage: build
  script:
    - npm run build:all
  artifacts:
    paths:
      - client/build

pages:
  stage: deploy
  script:
    - mv client/build public
  artifacts:
    paths:
      - public
  only:
    - main
