image: node:14

stages:
  - install
  - build

cache:
  paths:
    - client/node_modules/
    - Server/node_modules/

before_script:
  # Ensure npm dependencies are installed for both client and server
  - cd client && npm install && cd ..
  - if [ -d "Server" ]; then cd Server && npm install && cd ..; fi

install:
  stage: install
  script:
    - echo "Dependencies installed."

build:
  stage: build
  script:
    - npm run build:all
  artifacts:
    paths:
      - client/build
