image: node:14

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - client/node_modules/
    - server/node_modules/

before_script:
  - npm install

install:
  stage: install
  script:
    - npm run install:all

build:
  stage: build
  script:
    - npm run build:all
  artifacts:
    paths:
      - client/build

pages:
  stage: deploy
  script:
    - mv client/build public
  artifacts:
    paths:
      - public
  only:
    - main